name: "Composite Discord Notification"
description: "Sends a Discord notification based on the job status."

# アクションが受け取る入力パラメータを定義
inputs:
  webhook-url:
    description: "Discord webhook URL"
    required: true
  job-status:
    description: "The status of the job (e.g., success, failure, cancelled)"
    required: true
  mention-id:
    description: "Discord user ID to mention"
    required: true
  title:
    description: "Title of the notification embed"
    required: false
    default: "terraform"
  description:
    description: "Description of the notification embed"
    required: false
    default: ""
  success-color:
    description: "Color for success notifications (hex)"
    required: false
    default: "0x0000FF" # 青
  failure-color:
    description: "Color for failure notifications (hex)"
    required: false
    default: "0xFF0000" # 赤
  cancelled-color:
    description: "Color for cancelled notifications (hex)"
    required: false
    default: "0xFFFF00" # 黄

# アクションの実行内容
runs:
  using: "composite"
  steps:
    # 成功時の通知
    - name: Discord Notification For Success
      if: ${{ inputs.job-status == 'success' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ inputs.webhook-url }}
        username: GitHub Actions
        avatar_url: "https://github.com/actions.png"
        color: ${{ inputs.success-color }}
        content: "<@${{ inputs.mention-id }}>"
        status: ${{ inputs.job-status }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}

    # 失敗時の通知
    - name: Discord Notification For Failure
      if: ${{ inputs.job-status == 'failure' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ inputs.webhook-url }}
        username: GitHub Actions
        avatar_url: "https://github.com/actions.png"
        color: ${{ inputs.failure-color }}
        content: "<@${{ inputs.mention-id }}>"
        status: ${{ inputs.job-status }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}

    # キャンセル時の通知
    - name: Discord Notification For Cancelled
      if: ${{ inputs.job-status == 'cancelled' }}
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ inputs.webhook-url }}
        username: GitHub Actions
        avatar_url: "https://github.com/actions.png"
        color: ${{ inputs.cancelled-color }}
        content: "<@${{ inputs.mention-id }}>"
        status: ${{ inputs.job-status }}
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
