name: "Terraform CD"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      # AWS認証情報とTerraformバックエンド設定を環境変数として定義
      AWS_REGION: "ap-northeast-1"
      TF_VERSION: "1.12.2"

    steps:
      # 1. リポジトリ名だけを取得
      - name: Get repository name without owner
        id: repo_name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY#*/}" >> "$GITHUB_ENV"

      # 2. リポジトリのコードをチェックアウト
      - name: Checkout
        uses: actions/checkout@v4

      # 3. AWSのOIDC認証を設定
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      # 4. Terraform CLIのセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # 5. Terraformの初期化
      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ secrets.AWS_TF_STATE_BUCKET }}" \
            -backend-config="key=${REPO_NAME}/terraform.tfstate" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="use_lockfile=true"

      # 6. Terraformのフォーマットチェック
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      # 7. Terraformの適用
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
